Fix #5: Let the form field set widget choices
This fixes a bug caused by early evaluation of the queryset by the
Select field::

    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
        self.check()
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
        include_deployment_checks=include_deployment_checks,
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
        return check_resolver(resolver)
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
        for pattern in resolver.url_patterns:
      File "/home/jpic/env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/home/jpic/env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/jpic/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
        return import_module(self.urlconf_name)
      File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/jpic/env/src/addanother/test_project/urls.py", line 4, in <module>
        from views import AddView, FormView
      File "/home/jpic/env/src/addanother/test_project/views.py", line 8, in <module>
        from forms import TestForm
      File "/home/jpic/env/src/addanother/test_project/forms.py", line 8, in <module>
        class TestForm(forms.ModelForm):
      File "/home/jpic/env/src/addanother/test_project/forms.py", line 9, in TestForm
        class Meta:
      File "/home/jpic/env/src/addanother/test_project/forms.py", line 14, in Meta
        forms.SelectMultiple(choices=Group.objects.all()),
      File "/home/jpic/env/lib/python2.7/site-packages/django/forms/widgets.py", line 514, in __init__
        self.choices = list(choices)
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __iter__
        self._fetch_all()
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
        self._result_cache = list(self.iterator())
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
        results = compiler.execute_sql()
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
        cursor.execute(sql, params)
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/home/jpic/env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
        return Database.Cursor.execute(self, query, params)
    django.db.utils.OperationalError: no such table: auth_group